YusukeIwaki/capybara-playwright-driver

README.md
lib/capybara/playwright/browser.rb
lib/capybara/playwright/driver.rb
lib/capybara/playwright/node.rb
spec/feature/example_spec.rb

```
find('a[data-item-type="global_search"]').click
```
Capybara's selector and action (click, select_option, ...) is very flaky.
Because the finder selects nodes with `query_selector_all` and check the visibility with `visible?` **by polling with a bit sleep**.
Playwright introduces very relyable [auto-waiting feature](https://playwright.dev/docs/actionability/). We should use it instead of polling and sleep.
This PR adds 2 methods for exposing native playwright Page/ElementHandle instance

Introduce with_playwright_page and with_playwright_element_handle

---

lib/capybara/playwright/driver.rb
lib/capybara/playwright/node.rb
spec/capybara/playwright_spec.rb

The expectation of Capybara is often different from Playwright's expectation.
After #7 , we don't need to use Playwright internally in each selector/finder method. So import apparition's JS logics.

Make node delived from apparition

---

lib/capybara/playwright/browser.rb
spec/capybara/playwright_spec.rb

title and current_url should always return the information of Page even if within a frame.

Fix current_url, title to return page info

---

.circleci/config.yml
.github/workflows/rspec.yml

It seems Playwright 1.12 have breaking changes around `page.on("response")`
Keep using Playwright 1.11 at this point.

fix CI failure without reset! called

---

.github/workflows/rspec.yml
capybara-playwright.gemspec
lib/capybara/playwright/page.rb

playwright-ruby-client supports Ruby >= 2.4.
capybara-playwright-driver also support them.
Also fixes #29

Check example with various ruby versions

---

README.md
lib/capybara/playwright/node.rb
spec/feature/example_spec.rb

Capybara checks `visible?` before clicing the node.
Current implementation checks visibility without checking it the element is attached or not. Thus, it causes error:
```
Failures:
1) Example search capybara
Failure/Error: @element.click(**click_options.as_params)
Playwright::Error:
Error: Element is not attached to the DOM
=========================== logs ===========================
attempting click action
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

Increase stability on click

---

.github/workflows/rspec.yml

Playwright client (compatible with 1.11) cannot handle on request/response events with Playwright 1.12 driver.

Fix CI failure

---

lib/capybara/playwright/browser.rb
lib/capybara/playwright/node.rb
spec/capybara/playwright_spec.rb

Just triggering mouse events.
HTML5 drag (dragstart, dragleave, dragend, etc) is still not supported... waiting https://github.com/microsoft/playwright/pull/6207 to be merged.

Implement Node#drag_to

---

lib/capybara/playwright/browser.rb
lib/capybara/playwright/driver.rb

Existing Capybara drivers don't dispose a browser instance on reset.
* selenium: https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/driver.rb#L159
* cuprite: https://github.com/rubycdp/cuprite/blob/master/lib/capybara/cuprite/driver.rb#L152
* apparition: https://github.com/twalpole/apparition/blob/master/lib/capybara/apparition/driver.rb#L144
Currently capybara-playwright-driver disposes Browser for every test case. It is terriblly slow.

Reuse browser instance on reset_sessions!

---

lib/capybara/playwright/browser.rb
spec/capybara/playwright_spec.rb

```
node = @session.find(:css, '#change') # ensure page has loaded and element is available
res = node.evaluate_script(<<~JS, 3)
(function(n){
var el = this;
return [el, n];
}).apply(this, arguments)
JS
expect(res).to eq [node, 3]
```
Fix impl to convert the node to Capybara::Node::Element.

Fix evaluate_script to unwrap JS Array and object

---

capybara-playwright.gemspec
lib/capybara/playwright.rb
lib/capybara/playwright/browser_runner.rb
lib/capybara/playwright/driver.rb
spec/spec_helper.rb

resolves #43 
Playwright allows three methods for launching browser. This PR make it possible to run connect_to_playwright_server and connect_to_browser_server.
* **Playwright.create** (already available)
* **Playwright.connect_to_playwright_server** https://github.com/YusukeIwaki/playwright-ruby-client/pull/123 (requires playwright-ruby-client >= 0.8.0 and websocket-driver)
* **Playwright.connect_to_browser_server** https://github.com/YusukeIwaki/playwright-ruby-client/pull/155 (requires playwright-ruby-client >= 1.1.5.beta1 and websocket-driver)
---
connect_to_browser_server is tested, however shipped only as a beta release at this moment.
So this PR changes the minimum version of playwright-ruby-client to **0.8.0**.

Add options to execute Playwright.connect_to_playwright_server

---

lib/capybara/playwright/page_options.rb

Allow serviceWorkers option as a valid new_context option.
https://playwright-ruby-client.vercel.app/docs/api/browser#new_context

Add serviceWorkers to PageOptions

---

lib/capybara/playwright/browser.rb
lib/capybara/playwright/driver.rb
spec/feature/timeout_spec.rb

I noticed that  the `default_timeout` is not customizable while the `default_navigation_timeout ` is. It is probably not common to use `get_by_label` in Ruby, but it does have a use case (e.g. grabbing an input in a shadow root) and it may be more popular as people start utilizing new web APIs. The default 30s timeout is very long and I would like this to be customizable as well.

Allow for setting Playwright's default time out

---

spec/capybara/playwright_spec.rb

Official Capybara's spec also skip this spec for Firefox.

add pending for Firefox

---

lib/capybara/playwright/driver_extension.rb
spec/feature/tracing_spec.rb

Given the issue #65, it seems like there is some general interest in a simpler interface for using traces. The code in this PR is the code I use to test https://toprubycompanies.info in CI, and it's been working very well.
With the new interfaces introduced by this PR, using Playwright's trace is as simple as:
```ruby
class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
driven_by :playwright
setup do
page.driver.start_tracing(title: method_name) if retrying?
end
def before_teardown
if retrying?
page.driver.stop_tracing(path: "./tmp/playwright/traces/#{method_name}.zip"))
end
ensure
super
end
def retrying?
end
end
```
With RSpec, it could look like:
```ruby
around :example do |example|
if should_trace?
page.driver.trace path: …
```

Add helper methods for starting/stopping trace

---

lib/capybara/playwright/browser.rb
lib/capybara/playwright/driver.rb
lib/capybara/playwright/driver_extension.rb
spec/feature/example_spec.rb

closes #65 
This PR provides a simple and useful tracing option for Allure users.
```ruby
before do |example|
...
Capybara.current_session.driver.on_save_trace do |trace_path|
Allure.add_attachment(
name: "trace - #{example.description}",
source: File.read(trace_path),
type: 'application/zip',
test_case: true,
)
end
end
```

Provide a simple configuration for tracing

---

capybara-playwright.gemspec
lib/capybara/playwright/browser.rb
spec/feature/assertion_spec.rb

The following error occurs when the path contains 2-byte characters.
```
URI::InvalidURIError:
URI must be ascii only "http://localhost:4567/\u732B"
```
Referring to the Capybara implementation, use Addressable instead of URI
to support 2-byte characters.
refs: https://github.com/teamcapybara/capybara/blob/3.40.0/lib/capybara/session.rb#L261

Support paths using 2-byte characters

---

lib/capybara/playwright/node.rb

Some pages cause a `invalid byte sequence in UTF-8` exception to be raised when calling `text.to_s.gsub(/\A[[:space:]&&[^\u00a0]]+/, '')`. Adding [`scrub`](https://rubyapi.org/3.3/o/string#method-i-scrub) prevents this.
Specific context:
It seems a `&nbsp;` HTML entity gets interpreted as "\xA0", or byte 160, which has an invalid encoding. Using [`charlock_homes`](https://github.com/brianmario/charlock_holmes) the encoding of the entire page is reported as `ISO-8859-1` with 54% confidence.

Node#visible_text use scrub to replace invalid UTF-8 sequences

---

lib/capybara/playwright/driver_extension.rb
spec/feature/example_spec.rb

I want to use Playwright's API exclusively (without capybara's API), but I noticed that my tests would pass without doing anything unless I called `capybara's` visit first. 
I managed to track it down to the `@browser&.with_playwright_page`. So I replaced it with `browser` method, which seems to instantiate the browser.
I also think the save navigation here should be avoided. If `browser` is nil we should raise a no-method error instead of doing nothing.
This error is reproduced in specs, but I'm open for suggestions if you have an idea to do it better.

Fix silent test pass

---

lib/capybara/playwright/node.rb
spec/feature/example_spec.rb

This PR provides functionality that allows callers to specify lowercase keys in `send_keys`, something not currently supported as they are always uppercased unless they are sent as an individual string.
I'd like to write a test to validate behavior for opening a window with `send_keys [:control, 'k']`, but that's not possible because the keys are implicitly uppercased in this library. Note that this same command works using a Selenium driver.
A possible workaround for existing versions is below, but ought to be supported outright.
```ruby
page.driver.with_playwright_page do |page|
page.keyboard.press('Control+k') # note this isn't `press('Control+K')`
end
```
I've added a test to this PR that confirms the correct behavior on sites that include shortcuts with modifiers (Tailwind) and …

[Bugfix] Allow lowercase strings in `send_keys`

---

lib/capybara/playwright/node.rb
spec/feature/example_spec.rb

Fixes #88
This is a regression from https://github.com/YusukeIwaki/capybara-playwright-driver/pull/86, which is too wide-reaching in upper-casing keys combined with Shift. Instead, only explicitly uppercase the individual a-z keys that require it.

[Bugfix] Do not modify special keys

---

lib/capybara/playwright/node.rb

Do not override `:wait` when the current driver is not Playwright. This was causing our suite to fail just by requiring
`capybara-playwright-driver`.

Do not override `:wait` for non-Playwright drivers

---

lib/capybara/playwright/page.rb

Fixes https://github.com/YusukeIwaki/capybara-playwright-driver/issues/92

fix: typo in modal not found error message

---

lib/capybara/playwright/browser_options.rb

Fixes #99
Support the `reducedMotion` option.

Add reducedMotion to BrowserOption

---

lib/capybara/playwright/browser_options.rb
lib/capybara/playwright/page_options.rb

This is a fix for https://github.com/YusukeIwaki/capybara-playwright-driver/pull/100. The `reducedMotion` option is a `PageOption`, not `BrowserOption`.
For anyone blocked by this, you can add this to your playwright initialization:
```ruby
Capybara::Playwright::PageOptions::NEW_PAGE_PARAMS.push(:reducedMotion)
Capybara::Playwright::BrowserOptions::LAUNCH_PARAMS.delete(:reducedMotion)
```

Move reducedMotion to PageOption

---

capybara-playwright.gemspec

This gem does not expose any executables.

gemspec: Drop unused executables configuration
